### PR TITLE
onScroll: throttled only once, always perform after the DOM is ready

### PR DESCRIPTION
**Pull request by Mithgol**
The following changes are made:
- `onScroll` is throttled only once (otherwise two throttles happen independently of each other)
- not only one, but **every** `onScroll` is delayed until the DOM is ready (and throttled to ensure that `onScroll` is not called several times when the DOM becomes ready)
- each `$.scrollSpy(...)` call causes one `onScroll` call (throttled and DOM-delayed) regardless of the `isSpying` state (otherwise the second call and later `$.scrollSpy(...)` calls do not immediately trigger `scrollSpy:enter` on elements that are already “above the fold”)

The latter is actually a bugfix.

### CODE REVIEW

**Comment by thesmart** [comment]
I believe I have fixed your bug in the latest version.  Check it out if you like.

**Comment by Mithgol** [comment]
I've checked this out and seen only three commits after I made this patch:
- commit 45f15b93ca04385e63de18ca7283fb5e25452f23 adds the `.winSizeSpy` method
- commit e7725b4ad03b3a755e651d4f806457c9af958181 fixes typos in versions
- commit 442c780cf9f6351a9134688fe1f4111e6992266a highlights the JavaScript code in README

Where exactly is the fix for #5?

**Comment by Mithgol** [comment]
@thesmart ping

**Comment by thesmart** [comment]
thanks for reminding me, reviewing your commits now

**Comment by thesmart** [comment]
Pushed. Thanks!

**Comment by Mithgol** [comment]
Thanks for the manual merge!

For future references: these changes were merged in 0ae1076076b77707ecfc783fd8e460933a461b97.

**Pull request closed without merging**
